[Incident Report] Add template.
pumpupapp/code pull request #5
Opened 2017-06-16 00:28 UTC by rpavlovs

2017-06-16 00:30 UTC, Duelist commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Incident] Create a template for future incident reports.](https://trello.com/c/vxTy4UVa/174-incident-create-a-template-for-future-incident-reports)

2017-06-19 23:30 UTC, garrettg123 requested changes
👍

2017-06-19 23:30 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +## Resolution and recovery
`Recovery`

2017-06-19 23:30 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +* do not sugarcoat
Capitalize first letter of each point

2017-06-19 23:30 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +* what can we do better next time?
`* Add links to relevant Trello cards`

2017-06-19 23:30 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +* when service was restored
What if this was a list of times so the reader can copy the format?

2017-06-19 23:30 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +* close with root cause
Same here. Format this in sentences so the reader can copy the format.

2017-06-20 23:49 UTC, garrettg123 approved these changes
👍

2017-06-20 23:49 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +* June 14 02:08 PM: When staff was notified
`were`

2017-06-20 23:49 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +Give detailed explanation of actions taken (includes times)
`Give a detailed...`

2017-06-20 23:49 UTC, garrett-gottlieb commented on Incident Reports/template.md
> +Give detailed explanation of actions taken (includes times)
`(including times).`

2017-06-20 23:52 UTC, merged